Repository CherryHQ/cherry-studio-hmos-desktop, pull requests merged in 2025-05, with the labels that each got.

#5 鸿蒙目前不支持浏览器唤醒应用功能，隐藏设置 数据设置 坚果云 登录 #4
  src/renderer/src/pages/settings/DataSettings/DataSettings.tsx
Labels: Dev Team, sig/Data

#10 隐藏助手中的知识库和Mcp入口
  src/renderer/src/pages/settings/AssistantSettings/index.tsx
Labels: Dev Team, sig/RAG, sig/MCP

#8 隐藏检查更新和自动更新 功能
  src/renderer/src/hooks/useAppInit.ts
  src/renderer/src/pages/settings/AboutSettings.tsx
Labels: Dev Team

#14 显示知识库和Mcp入口
  src/renderer/src/App.tsx
  src/renderer/src/components/app/Sidebar.tsx
  src/renderer/src/pages/home/Inputbar/Inputbar.tsx
  src/renderer/src/pages/settings/AssistantSettings/index.tsx
  src/renderer/src/pages/settings/SettingsPage.tsx
  src/renderer/src/store/settings.ts
Labels: Dev Team, sig/RAG, sig/MCP

#18 修复对话导航按钮
  src/renderer/src/pages/home/Messages/ChatNavigation.tsx
Labels: Dev Team, area/UI/UX

#22 修改上一个提交
  src/renderer/src/pages/home/Inputbar/Inputbar.tsx
Labels: Dev Team
